name: Setup gdrive
description: Setup/Install gdrive (Google Drive CLI Client) for GitHub Actions
branding:
  icon: upload-cloud
  color: green
inputs:
  service_account:
    description: Google service account JSON in base64
    required: true
  version:
    description: Version of gdrive
    required: false
    default: '2.1.2'
    
runs:
  using: composite
  steps:
    - name: Download gdrive binaries
      shell: bash
      working-directory: ${{ runner.temp }}
      run: aria2c -x 16 "https://github.com/trinvh/gdrive/releases/download/${{ inputs.version }}/gdrive_${{ inputs.version }}_linux_386.tar.gz" # Issue 597
      
    - name: Extract gdrive binaries
      shell: bash
      working-directory: ${{ runner.temp }}
      run: tar -xzf "gdrive_${{ inputs.version }}_linux_386.tar.gz"
      
    - name: Install gdrive on /usr/local/bin/
      shell: bash
      run: mv $RUNNER_TEMP/gdrive /usr/local/bin/
      
    - name: Sign in to Google Drive using service account JSON file
      shell: bash
      env:
        service_account: ${{ inputs.service_account }}
      run: |
        mkdir ~/.gdrive
        echo $service_account | base64 -d > ~/.gdrive/gdrive.json
        gdrive --service-account gdrive.json about
        
    - name: Clean up
      shell: bash
      working-directory: ${{ runner.temp }}
      run: rm gdrive_${{ inputs.version }}_linux_386.tar.gz
