name: Test setup-gdrive
on:
  push:
    paths:
      - action.yml
      - .github/workflows/test.yaml
    tags-ignore:
      - v*
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gdrive using setup-gdrive
        uses: AnimMouse/setup-gdrive@main
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          
      - name: Test gdrive installed by setup-gdrive
        run: gdrive --service-account gdrive.json about